version: '3'
services:
  db:
    build:
      context: ./DB
  backend1:
    build:
      context: ./backend
    depends_on:
      - db
  backend2:
    build:
      context: ./backend
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    ports:
      - '8080:80'
      