name: Database Ci

on:
  push:
    branches: [ "master" ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build image
      working-directory: DB
      run: |
        docker build . -t kevinlee584/librarysystem-db:latest

    - name: publish
      run: |
        docker login -u kevinlee584 -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push kevinlee584/librarysystem-db:latest