name: Vue Ci

on:
  push:
    branches: [ "master" ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
      
    - name: build 
      working-directory: frontend
      run: |
          npm ci
          npm run build

    - name: build image
      run: |
        cd ./frontend
        docker build . -t kevinlee584/librarysystem-frontend:latest
    - name: publish
      run: |
        docker login -u kevinlee584 -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push kevinlee584/librarysystem-frontend:latest